CREATE TABLE behavior_events (
    id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    event_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    actor_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    user_session_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    game_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    game_version_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    generation_run_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    share_link_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    play_session_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    request_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NULL,
    client_event_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    properties JSON NOT NULL,
    occurred_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_behavior_events_client_event_id (client_event_id),
    KEY idx_behavior_events_created_id (created_at, id),
    KEY idx_behavior_events_event_created_id (event_name, created_at, id),
    KEY idx_behavior_events_user_created_id (user_id, created_at, id),
    KEY idx_behavior_events_game_created_id (game_id, created_at, id),
    KEY idx_behavior_events_play_session_created_id (play_session_id, created_at, id),
    CONSTRAINT chk_behavior_events_source CHECK (source IN ('frontend', 'api', 'worker')),
    CONSTRAINT chk_behavior_events_actor_type CHECK (actor_type IN ('creator', 'receiver', 'system')),
    CONSTRAINT chk_behavior_events_properties CHECK (JSON_TYPE(properties) = 'OBJECT'),
    CONSTRAINT fk_behavior_events_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
